/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.unicauca.clientproducthttpclient.presentation;

import com.unicauca.clientproducthttpclient.controllers.CategoryController;
import com.unicauca.clientproducthttpclient.domain.entities.Category;
import com.unicauca.clientproducthttpclient.util.Messages;

/**
 *
 * @author Juan
 */
public class GUICategory extends javax.swing.JFrame {
    private CategoryController categoryController;
    boolean addOption;
    boolean deleteOption;
    boolean editOption;

    /**
     * Creates new form GUICategory
     */
    public GUICategory(CategoryController categoryController) {
        this.addOption=false;
        this.deleteOption=false;
        this.editOption=false;
        initComponents();
        this.categoryController=categoryController;
        stateInitial();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        pnlCenter = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        pnlSur = new javax.swing.JPanel();
        btnGrabar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Gestión de Categorias");
        getContentPane().add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pnlCenter.setPreferredSize(new java.awt.Dimension(128, 66));
        pnlCenter.setLayout(new java.awt.GridLayout(2, 2));

        lblId.setText("Id:");
        pnlCenter.add(lblId);
        lblId.getAccessibleContext().setAccessibleName("lblId");

        pnlCenter.add(txtId);

        lblName.setText("Nombre:");
        pnlCenter.add(lblName);
        pnlCenter.add(txtNombre);

        getContentPane().add(pnlCenter, java.awt.BorderLayout.CENTER);

        pnlSur.setMinimumSize(new java.awt.Dimension(392, 33));
        pnlSur.setPreferredSize(new java.awt.Dimension(392, 33));

        btnGrabar.setText("Grabar");
        btnGrabar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrabarActionPerformed(evt);
            }
        });
        pnlSur.add(btnGrabar);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        pnlSur.add(btnAgregar);

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        pnlSur.add(btnCancelar);

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        pnlSur.add(btnEditar);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        pnlSur.add(btnEliminar);

        btnListar.setText("Listar");
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarActionPerformed(evt);
            }
        });
        pnlSur.add(btnListar);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlSur.add(btnCerrar);

        getContentPane().add(pnlSur, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateInitial() {
        btnAgregar.setVisible(true);
        btnEditar.setVisible(true);
        btnEliminar.setVisible(true);
        btnCancelar.setVisible(false);
        btnCerrar.setVisible(true);
        btnGrabar.setVisible(false);
        btnListar.setVisible(true);
        txtId.setEnabled(false);
        txtNombre.setEnabled(false);

    }

    private void stateCreate() {
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        btnCancelar.setVisible(true);
        btnCerrar.setVisible(true);
        btnGrabar.setVisible(true);
        btnListar.setVisible(false);
        txtId.setEnabled(false);
        txtNombre.setEnabled(true);
    }

    private void stateEdit() {
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        btnCancelar.setVisible(true);
        btnCerrar.setVisible(true);
        btnGrabar.setVisible(true);
        btnListar.setVisible(false);
        txtId.setEnabled(true);
        txtNombre.setEnabled(true);
    }

    private void stateDelete() {
        btnAgregar.setVisible(false);
        btnEditar.setVisible(false);
        btnEliminar.setVisible(false);
        btnCancelar.setVisible(true);
        btnCerrar.setVisible(true);
        btnGrabar.setVisible(true);
        btnListar.setVisible(false);
        txtId.setEnabled(true);
        txtNombre.setEnabled(false);

    }

    private void cleanControls() {
        txtId.setText("");
        txtNombre.setText("");
    }
    private void btnListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarActionPerformed
        GUICategoryList dialog = new GUICategoryList(new javax.swing.JFrame(), true, this.categoryController);
        dialog.setSize(500, 200);
        dialog.setVisible(true);
    }//GEN-LAST:event_btnListarActionPerformed

    private void addCategory() {
        Category category = new Category();
        category.setCategoryId(0);
        category.setName(txtNombre.getText());
        categoryController.create(category);
        cleanControls();
        stateInitial();
    }
    
    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        stateCreate();
        this.addOption=true;
    }//GEN-LAST:event_btnAgregarActionPerformed
    
    private void editCategory() {
        Category categoryUpdated = new Category(txtNombre.getText());
        categoryController.edit(Integer.parseInt(txtId.getText()), categoryUpdated);
        cleanControls();
        stateInitial();
    }
    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        stateEdit();
        this.editOption=true;
    }//GEN-LAST:event_btnEditarActionPerformed

    private void deleteCategory() {
        categoryController.delete(Integer.parseInt(txtId.getText()));
        cleanControls();
        stateInitial();
    }
    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        stateDelete();
        this.deleteOption = true;
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGrabarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrabarActionPerformed
        if (deleteOption) {
            if (!validarId()) {
                return;
            }
            deleteCategory();
            deleteOption = false;
        }

        if (addOption) {
            if (!validarNombre()) {
                return;
            }
            addCategory();
            addOption = false;
        }

        if (editOption) {
            if (!validarCampos()) {
                return;
            }
            editCategory();
            editOption = false;
        }
    }//GEN-LAST:event_btnGrabarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        stateInitial();
        cleanControls();
    }//GEN-LAST:event_btnCancelarActionPerformed
    
        private boolean validarId() {
        String idText = txtId.getText().trim();
        if (idText.isEmpty()) {
            Messages.showMessageDialog("Debe ingresar el ID del producto", "Atención");
            txtId.requestFocus();
            return false;
        }
        try {
            Integer.parseInt(idText);
            return true;
        } catch (NumberFormatException e) {
            Messages.showMessageDialog("El ID debe ser un número entero válido", "Atención");
            txtId.requestFocus();
            return false;
        }
    }
    private boolean validarNombre() {
        if (txtNombre.getText().trim().isEmpty()) {
            Messages.showMessageDialog("Debe ingresar el nombre del producto", "Atención");
            txtNombre.requestFocus();
            return false;
        }
        return true;
    }
    
    private boolean validarCampos() {
        return validarNombre() && validarId();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGrabar;
    private javax.swing.JButton btnListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnlCenter;
    private javax.swing.JPanel pnlSur;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
