/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */
package com.unicauca.clientproducthttpclient.presentation;

import co.unicauca.microkernel.common.payhuynseda.Payment;
import com.unicauca.clientproducthttpclient.domain.entities.Item;
import com.unicauca.clientproducthttpclient.domain.services.PayServices;
import com.unicauca.clientproducthttpclient.util.Messages;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.UnsupportedEncodingException;
import java.net.URLDecoder;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import unicauca.microkernel.plugin.manager.DeliveryPluginManager;

/**
 *
 * @author jvuan
 */
public class GUIPago extends javax.swing.JFrame {
    
    List<Item> cart;

    /**
     * Creates new customizer GUIPago
     */
    
    public GUIPago(List<Item> cart) {
        this.cart = cart;
        initComponents();
        setLocationRelativeTo(null);
        this.setPreferredSize(new Dimension(400, 200));
    }
    private static String getBaseFilePath() {
        try {
            String path = GUIPago.class.getProtectionDomain().getCodeSource().getLocation().getPath();
            path = URLDecoder.decode(path, "UTF-8"); //This should solve the problem with spaces and special characters.
            File pathFile = new File(path);
            if (pathFile.isFile()) {
                path = pathFile.getParent();
                if (!path.endsWith(File.separator)) {
                    path += File.separator;
                }
            }
            return path;
        } catch (UnsupportedEncodingException ex) {
            Logger.getLogger(GUIPago.class.getName()).log(Level.SEVERE, "Error al eliminar espacios en la ruta del archivo", ex);
            return null;
        }
    }
    public GUIPago() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setTitle("Método de Pago"); // Establece el título de la ventana
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE); // Cierra la ventana cuando se presiona la X

        // Crea un panel principal con GridBagLayout para organizar los componentes
        JPanel mainPanel = new JPanel(new GridBagLayout());
        getContentPane().add(mainPanel, BorderLayout.CENTER);

        // Crea los componentes
        jLabel2 = new JLabel("Método de Pago");
        jLabel2.setFont(new Font("SansSerif", Font.BOLD, 18));

        jComboBox2 = new JComboBox<>(new String[]{"PSE", "Efecty", "MasterCard"});

        btnPagar = new JButton("Pagar");
        btnPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPagarActionPerformed(evt);
            }
        });

        btnCerrar = new JButton("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        // Agrega los componentes al panel principal usando GridBagConstraints
        GridBagConstraints constraints = new GridBagConstraints();
        constraints.gridx = 0;
        constraints.gridy = 0;
        constraints.anchor = GridBagConstraints.CENTER;
        constraints.insets = new Insets(10, 10, 10, 10);
        mainPanel.add(jLabel2, constraints);

        constraints.gridy = 1;
        constraints.gridx = 0;
        constraints.gridwidth = 1;
        mainPanel.add(jComboBox2, constraints);

        constraints.gridx = 1;
        mainPanel.add(btnPagar, constraints);

        constraints.gridy = 2;
        constraints.gridx = 0;
        constraints.gridwidth = GridBagConstraints.REMAINDER;
        constraints.anchor = GridBagConstraints.CENTER;
        mainPanel.add(btnCerrar, constraints);

        pack(); // Ajusta el tamaño de la ventana según los componentes
        setLocationRelativeTo(null); // Centra la ventana en la pantalla
    }// </editor-fold>//GEN-END:initComponents

    private void btnPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPagarActionPerformed
        // TODO add your handling code here:
        
        //double charge = 0;

        //for (ItemShoppingCart p : cart)
        //{
            //    charge = charge + p.getProduct().getPrice()*p.getAmount();
            //}

        String method = jComboBox2.getSelectedItem().toString();

        String basePath = getBaseFilePath();
        try {
            DeliveryPluginManager.init(basePath);
            //Console presentationObject = new Console();
            //presentationObject.start();

            Payment pay = new Payment (method, 12345, 1000000);
            PayServices payServices = new PayServices();
            boolean paymentVerified = payServices.verifyPayment(pay);

            if (paymentVerified) {
                JOptionPane.showMessageDialog(this, "Pago realizado con éxito"); // Mostrar mensaje de éxito
                Messages.sendPaymentConfirmationMessage();
                
            } else {
                JOptionPane.showMessageDialog(this, "Error al procesar el pago", "Error", JOptionPane.ERROR_MESSAGE); // Mostrar mensaje de error
            }

        } catch (Exception ex) {
            Logger.getLogger("GUIPago").log(Level.SEVERE, "Error al ejecutar la aplicación", ex);
        }
    }//GEN-LAST:event_btnPagarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnPagar;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
